spring.application.name=Proyecto

spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver
spring.datasource.url = jdbc:mysql://localhost:3306/bdServiciosSoap
spring.datasource.username = root
spring.datasource.password = mysql

spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true

sunat.ruc=20601234567
sunat.usuario-sol=MODDATOS
sunat.clave-sol=moddatos
sunat.endpoint=//e-beta.sunat.gob.pe/ol-ti-itcpfegem-beta/billService
sunat.certificado=certificado.pfx
sunat.certificado-password=123456
